import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="py-4 px-12 flex justify-between">
          <Link href="/">
            <h1>Easy Sell 💸</h1>
          </Link>
          <button>Upload</button>
        </header>
        <hr className="h-1 bg-purple-300 border-0 dark:bg-gray-700"></hr>
        {children}
      </body>
    </html>
  );
}
